# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, Manikanta!
  displayName: 'Run a one-line script'

- script: ls -al && pwd
  displayName: 'List Files and Show Present WOrking Directory'

- script: echo "The Build ID is $(Build.BuildID) with Build Number $(Build.BuildNumber)"
  displayName: 'Displaying BuildID and Build Number' 

- script: sudo apt update && sudo apt install openjdk-8-jdk && java -version
  displayName: 'Installing Java and Checking It'

- script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
  displayName: 'Running the build file and checking it'